"""Tests for multi-provider Copilot AI architecture with fallback.

Covers all 11 required scenarios:
1. Gemini key empty → Groq attempted.
2. Gemini unavailable (503) → Groq attempted.
3. Gemini succeeds → Groq not called.
4. Gemini fails (500) → Groq succeeds.
5. Gemini fails → Groq fails → deterministic fallback.
6. Both API keys empty → deterministic fallback (0 HTTP requests).
7. Invalid Gemini response → Groq fallback.
8. Gemini timeout → Groq fallback.
9. Groq timeout → deterministic fallback.
10. Source references remain intact.
11. Existing Copilot behavior still works without AI providers.
"""

import uuid
from datetime import UTC, datetime

import httpx
import pytest
from pydantic import SecretStr

from app.api.schemas import AnswerItem, CopilotAnswer, SourceRef
from app.core.config import Settings
from app.services.copilot_providers import (
    CopilotContext,
    create_copilot_router,
)


def make_dummy_context(
    question: str = "What is the fixed rate on Riverbend?",
    deal_name: str | None = "The Lofts at Riverbend",
    intent: str = "lowest_fixed_rate",
) -> CopilotContext:
    email_id = uuid.uuid4()
    ref = SourceRef(
        email_id=email_id,
        email_subject="Beacon term sheet",
        email_sender="jsmith@beaconagency.com",
        email_sent_at=datetime(2026, 10, 3, 12, 0, tzinfo=UTC),
        source_text="10-year fixed at 5.12%",
        label="Interest rate",
    )
    items = [
        AnswerItem(
            title="Beacon Agency Lending",
            text="5.12% fixed",
            deal_id=uuid.uuid4(),
            sources=[ref],
        )
    ]
    return CopilotContext(
        question=question,
        deal_id=uuid.uuid4(),
        deal_name=deal_name,
        intent=intent,
        items=items,
        context_text="[1] (FIELD) Interest rate: 5.12% — Beacon Agency Lending | Source: Beacon term sheet",
    )


async def dummy_fallback(context: CopilotContext) -> CopilotAnswer:
    return CopilotAnswer(
        question=context.question,
        intent=context.intent,
        mode="structured",
        deal_id=context.deal_id,
        deal_name=context.deal_name,
        answer="The lowest fixed rate on The Lofts at Riverbend is 5.12% from Beacon Agency Lending.",
        items=context.items,
    )


# ---------------------------------------------------------------- Test Scenarios


@pytest.mark.anyio
async def test_1_gemini_key_empty_groq_attempted(caplog) -> None:
    settings = Settings(
        gemini_api_key=None,
        groq_api_key=SecretStr("mock-groq-key"),
        copilot_provider_order="gemini,groq,deterministic",
    )

    gemini_called = False
    groq_called = False

    def transport_handler(request: httpx.Request) -> httpx.Response:
        nonlocal gemini_called, groq_called
        if "generativelanguage.googleapis.com" in str(request.url):
            gemini_called = True
            return httpx.Response(200, json={})
        if "api.groq.com" in str(request.url):
            groq_called = True
            return httpx.Response(
                200,
                json={"choices": [{"message": {"content": "Answer generated by Groq."}}]},
            )
        return httpx.Response(404)

    client = httpx.AsyncClient(transport=httpx.MockTransport(transport_handler))
    router = create_copilot_router(fallback_fn=dummy_fallback, settings=settings, http_client=client)

    with caplog.at_level("INFO"):
        answer = await router.answer(make_dummy_context())

    assert not gemini_called, "Gemini must not be called when API key is empty"
    assert groq_called, "Groq must be attempted when Gemini key is empty"
    assert answer.mode == "llm"
    assert answer.answer == "Answer generated by Groq."
    assert "Gemini unavailable → trying Groq" in caplog.text


@pytest.mark.anyio
async def test_2_gemini_unavailable_groq_attempted(caplog) -> None:
    settings = Settings(
        gemini_api_key=SecretStr("mock-gemini-key"),
        groq_api_key=SecretStr("mock-groq-key"),
        copilot_provider_order="gemini,groq,deterministic",
    )

    def transport_handler(request: httpx.Request) -> httpx.Response:
        if "generativelanguage.googleapis.com" in str(request.url):
            return httpx.Response(503, json={"error": "Service Unavailable"})
        if "api.groq.com" in str(request.url):
            return httpx.Response(
                200,
                json={"choices": [{"message": {"content": "Groq answer after Gemini 503."}}]},
            )
        return httpx.Response(404)

    client = httpx.AsyncClient(transport=httpx.MockTransport(transport_handler))
    router = create_copilot_router(fallback_fn=dummy_fallback, settings=settings, http_client=client)

    with caplog.at_level("WARNING"):
        answer = await router.answer(make_dummy_context())

    assert answer.mode == "llm"
    assert answer.answer == "Groq answer after Gemini 503."
    assert "Gemini unavailable (HTTP 503) → trying Groq" in caplog.text


@pytest.mark.anyio
async def test_3_gemini_succeeds_groq_not_called() -> None:
    settings = Settings(
        gemini_api_key=SecretStr("mock-gemini-key"),
        groq_api_key=SecretStr("mock-groq-key"),
        copilot_provider_order="gemini,groq,deterministic",
    )

    gemini_calls = 0
    groq_calls = 0

    def transport_handler(request: httpx.Request) -> httpx.Response:
        nonlocal gemini_calls, groq_calls
        if "generativelanguage.googleapis.com" in str(request.url):
            gemini_calls += 1
            return httpx.Response(
                200,
                json={"candidates": [{"content": {"parts": [{"text": "Gemini primary answer."}]}}]},
            )
        if "api.groq.com" in str(request.url):
            groq_calls += 1
            return httpx.Response(200, json={})
        return httpx.Response(404)

    client = httpx.AsyncClient(transport=httpx.MockTransport(transport_handler))
    router = create_copilot_router(fallback_fn=dummy_fallback, settings=settings, http_client=client)

    answer = await router.answer(make_dummy_context())

    assert gemini_calls == 1
    assert groq_calls == 0, "Groq must not be called when Gemini succeeds"
    assert answer.mode == "llm"
    assert answer.answer == "Gemini primary answer."


@pytest.mark.anyio
async def test_4_gemini_fails_groq_succeeds(caplog) -> None:
    settings = Settings(
        gemini_api_key=SecretStr("mock-gemini-key"),
        groq_api_key=SecretStr("mock-groq-key"),
        copilot_provider_order="gemini,groq,deterministic",
    )

    def transport_handler(request: httpx.Request) -> httpx.Response:
        if "generativelanguage.googleapis.com" in str(request.url):
            return httpx.Response(500, json={"error": "Internal Error"})
        if "api.groq.com" in str(request.url):
            return httpx.Response(
                200,
                json={"choices": [{"message": {"content": "Groq successful response."}}]},
            )
        return httpx.Response(404)

    client = httpx.AsyncClient(transport=httpx.MockTransport(transport_handler))
    router = create_copilot_router(fallback_fn=dummy_fallback, settings=settings, http_client=client)

    with caplog.at_level("WARNING"):
        answer = await router.answer(make_dummy_context())

    assert answer.mode == "llm"
    assert answer.answer == "Groq successful response."
    assert "Gemini unavailable (HTTP 500) → trying Groq" in caplog.text


@pytest.mark.anyio
async def test_5_gemini_fails_groq_fails_deterministic_fallback(caplog) -> None:
    settings = Settings(
        gemini_api_key=SecretStr("mock-gemini-key"),
        groq_api_key=SecretStr("mock-groq-key"),
        copilot_provider_order="gemini,groq,deterministic",
    )

    def transport_handler(request: httpx.Request) -> httpx.Response:
        if "generativelanguage.googleapis.com" in str(request.url):
            return httpx.Response(500, json={"error": "Gemini 500"})
        if "api.groq.com" in str(request.url):
            return httpx.Response(500, json={"error": "Groq 500"})
        return httpx.Response(404)

    client = httpx.AsyncClient(transport=httpx.MockTransport(transport_handler))
    router = create_copilot_router(fallback_fn=dummy_fallback, settings=settings, http_client=client)

    with caplog.at_level("WARNING"):
        answer = await router.answer(make_dummy_context())

    assert answer.mode == "structured"
    assert "The lowest fixed rate on The Lofts at Riverbend" in answer.answer
    assert "Gemini unavailable (HTTP 500) → trying Groq" in caplog.text
    assert "Groq unavailable (HTTP 500) → using deterministic fallback" in caplog.text


@pytest.mark.anyio
async def test_6_both_api_keys_empty_deterministic_fallback(caplog) -> None:
    settings = Settings(
        gemini_api_key=None,
        groq_api_key=None,
        copilot_provider_order="gemini,groq,deterministic",
    )

    requests_made = 0

    def transport_handler(request: httpx.Request) -> httpx.Response:
        nonlocal requests_made
        requests_made += 1
        return httpx.Response(200, json={})

    client = httpx.AsyncClient(transport=httpx.MockTransport(transport_handler))
    router = create_copilot_router(fallback_fn=dummy_fallback, settings=settings, http_client=client)

    with caplog.at_level("INFO"):
        answer = await router.answer(make_dummy_context())

    assert requests_made == 0, "No network requests should be made when both keys are empty"
    assert answer.mode == "structured"
    assert "The lowest fixed rate on The Lofts at Riverbend" in answer.answer
    assert "Gemini unavailable → trying Groq" in caplog.text
    assert "Groq unavailable → using deterministic fallback" in caplog.text


@pytest.mark.anyio
async def test_7_invalid_gemini_response_groq_fallback(caplog) -> None:
    settings = Settings(
        gemini_api_key=SecretStr("mock-gemini-key"),
        groq_api_key=SecretStr("mock-groq-key"),
        copilot_provider_order="gemini,groq,deterministic",
    )

    def transport_handler(request: httpx.Request) -> httpx.Response:
        if "generativelanguage.googleapis.com" in str(request.url):
            # Missing candidates array or empty parts
            return httpx.Response(200, json={"candidates": []})
        if "api.groq.com" in str(request.url):
            return httpx.Response(
                200,
                json={"choices": [{"message": {"content": "Recovered by Groq."}}]},
            )
        return httpx.Response(404)

    client = httpx.AsyncClient(transport=httpx.MockTransport(transport_handler))
    router = create_copilot_router(fallback_fn=dummy_fallback, settings=settings, http_client=client)

    with caplog.at_level("WARNING"):
        answer = await router.answer(make_dummy_context())

    assert answer.mode == "llm"
    assert answer.answer == "Recovered by Groq."
    assert "Gemini unavailable (invalid response: ValueError) → trying Groq" in caplog.text


@pytest.mark.anyio
async def test_8_gemini_timeout_groq_fallback(caplog) -> None:
    settings = Settings(
        gemini_api_key=SecretStr("mock-gemini-key"),
        groq_api_key=SecretStr("mock-groq-key"),
        copilot_provider_order="gemini,groq,deterministic",
    )

    def transport_handler(request: httpx.Request) -> httpx.Response:
        if "generativelanguage.googleapis.com" in str(request.url):
            raise httpx.ReadTimeout("Gemini read timeout")
        if "api.groq.com" in str(request.url):
            return httpx.Response(
                200,
                json={"choices": [{"message": {"content": "Groq answered after Gemini timeout."}}]},
            )
        return httpx.Response(404)

    client = httpx.AsyncClient(transport=httpx.MockTransport(transport_handler))
    router = create_copilot_router(fallback_fn=dummy_fallback, settings=settings, http_client=client)

    with caplog.at_level("WARNING"):
        answer = await router.answer(make_dummy_context())

    assert answer.mode == "llm"
    assert answer.answer == "Groq answered after Gemini timeout."
    assert "Gemini unavailable (timeout after 30.0s) → trying Groq" in caplog.text


@pytest.mark.anyio
async def test_9_groq_timeout_deterministic_fallback(caplog) -> None:
    settings = Settings(
        gemini_api_key=None,  # Gemini skipped
        groq_api_key=SecretStr("mock-groq-key"),
        copilot_provider_order="gemini,groq,deterministic",
    )

    def transport_handler(request: httpx.Request) -> httpx.Response:
        if "api.groq.com" in str(request.url):
            raise httpx.ReadTimeout("Groq read timeout")
        return httpx.Response(404)

    client = httpx.AsyncClient(transport=httpx.MockTransport(transport_handler))
    router = create_copilot_router(fallback_fn=dummy_fallback, settings=settings, http_client=client)

    with caplog.at_level("WARNING"):
        answer = await router.answer(make_dummy_context())

    assert answer.mode == "structured"
    assert "Groq unavailable (timeout after 30.0s) → using deterministic fallback" in caplog.text


@pytest.mark.anyio
async def test_10_source_references_remain_intact() -> None:
    # Test that both LLM answers and deterministic answers preserve genuine SourceRef objects
    settings = Settings(
        gemini_api_key=SecretStr("mock-gemini-key"),
        groq_api_key=None,
    )

    def transport_handler(request: httpx.Request) -> httpx.Response:
        return httpx.Response(
            200,
            json={"candidates": [{"content": {"parts": [{"text": "Beacon offered 5.12% fixed."}]}}]},
        )

    client = httpx.AsyncClient(transport=httpx.MockTransport(transport_handler))
    router = create_copilot_router(fallback_fn=dummy_fallback, settings=settings, http_client=client)

    context = make_dummy_context()
    original_sources = context.items[0].sources

    answer = await router.answer(context)

    assert len(answer.items) == 1
    assert len(answer.items[0].sources) == 1
    src = answer.items[0].sources[0]
    assert src.email_subject == "Beacon term sheet"
    assert src.email_sender == "jsmith@beaconagency.com"
    assert src.source_text == "10-year fixed at 5.12%"
    assert src.label == "Interest rate"
    assert src.email_id == original_sources[0].email_id


@pytest.mark.anyio
async def test_11_existing_copilot_behavior_still_works_without_ai_providers() -> None:
    # When keys are empty, create_copilot_router routes directly to the fallback function
    settings = Settings(gemini_api_key=None, groq_api_key=None)

    called = False

    async def verify_fallback(ctx: CopilotContext) -> CopilotAnswer:
        nonlocal called
        called = True
        return CopilotAnswer(
            question=ctx.question,
            intent=ctx.intent,
            mode="structured",
            deal_id=ctx.deal_id,
            deal_name=ctx.deal_name,
            answer="Existing deterministic output",
            items=ctx.items,
        )

    router = create_copilot_router(fallback_fn=verify_fallback, settings=settings)
    answer = await router.answer(make_dummy_context())

    assert called is True
    assert answer.mode == "structured"
    assert answer.answer == "Existing deterministic output"
