"""gmail integration tables

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-01 06:31:24.647177

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gmail_accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email_address", sa.Text(), nullable=False),
        sa.Column("refresh_token_encrypted", sa.Text(), nullable=False),
        sa.Column("scopes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "connected_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_scanned", sa.Integer(), nullable=False),
        sa.Column("last_sync_new", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gmail_accounts")),
        sa.UniqueConstraint("email_address", name=op.f("uq_gmail_accounts_email_address")),
    )
    op.create_table(
        "gmail_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("gmail_id", sa.String(length=64), nullable=False),
        sa.Column("thread_id", sa.String(length=64), nullable=True),
        sa.Column("email_id", sa.Uuid(), nullable=True),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("sender_name", sa.Text(), nullable=True),
        sa.Column("sender_email", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("snippet", sa.Text(), nullable=False),
        sa.Column("label_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attachment_names", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("relevance", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["gmail_accounts.id"],
            name=op.f("fk_gmail_messages_account_id_gmail_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["email_id"], ["emails.id"], name=op.f("fk_gmail_messages_email_id_emails"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gmail_messages")),
        sa.UniqueConstraint("account_id", "gmail_id", name=op.f("uq_gmail_messages_account_id")),
    )
    op.create_index(op.f("ix_gmail_messages_account_id"), "gmail_messages", ["account_id"], unique=False)
    op.create_index(op.f("ix_gmail_messages_email_id"), "gmail_messages", ["email_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gmail_messages_email_id"), table_name="gmail_messages")
    op.drop_index(op.f("ix_gmail_messages_account_id"), table_name="gmail_messages")
    op.drop_table("gmail_messages")
    op.drop_table("gmail_accounts")
    # ### end Alembic commands ###
