"""email intelligence tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-28 10:30:54.369746

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("deal_name", sa.Text(), nullable=False),
        sa.Column("property_name", sa.Text(), nullable=True),
        sa.Column("property_address", sa.Text(), nullable=True),
        sa.Column("city", sa.Text(), nullable=True),
        sa.Column("state", sa.Text(), nullable=True),
        sa.Column("property_type", sa.String(length=40), nullable=True),
        sa.Column("transaction_type", sa.String(length=40), nullable=True),
        sa.Column("sponsor_name", sa.Text(), nullable=True),
        sa.Column("broker_name", sa.Text(), nullable=True),
        sa.Column("purchase_price", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("property_value", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("loan_amount_requested", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("noi", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("cap_rate", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("units", sa.Integer(), nullable=True),
        sa.Column("square_feet", sa.Integer(), nullable=True),
        sa.Column("year_built", sa.Integer(), nullable=True),
        sa.Column("occupancy_pct", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("target_ltv", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("target_closing_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deals")),
    )
    op.create_table(
        "lenders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.Column("contact_name", sa.Text(), nullable=True),
        sa.Column("contact_email", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lenders")),
        sa.UniqueConstraint("normalized_name", name=op.f("uq_lenders_normalized_name")),
    )
    op.create_table(
        "emails",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("sender_email", sa.Text(), nullable=True),
        sa.Column("sender_name", sa.Text(), nullable=True),
        sa.Column("recipients", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("body_text", sa.Text(), nullable=False),
        sa.Column("raw_source", sa.Text(), nullable=False),
        sa.Column("in_reply_to", sa.Text(), nullable=True),
        sa.Column("references", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("filename", sa.Text(), nullable=True),
        sa.Column("deal_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("email_type", sa.String(length=40), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("raw_extraction", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["deal_id"], ["deals.id"], name=op.f("fk_emails_deal_id_deals"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_emails")),
        sa.UniqueConstraint("content_hash", name=op.f("uq_emails_content_hash")),
        sa.UniqueConstraint("message_id", name=op.f("uq_emails_message_id")),
    )
    op.create_index(op.f("ix_emails_deal_id"), "emails", ["deal_id"], unique=False)
    op.create_table(
        "extracted_values",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_email_id", sa.Uuid(), nullable=False),
        sa.Column("deal_id", sa.Uuid(), nullable=True),
        sa.Column("entity_type", sa.String(length=20), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("field_name", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("raw_value", sa.Text(), nullable=False),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["deal_id"], ["deals.id"], name=op.f("fk_extracted_values_deal_id_deals"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_email_id"],
            ["emails.id"],
            name=op.f("fk_extracted_values_source_email_id_emails"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extracted_values")),
    )
    op.create_index(op.f("ix_extracted_values_deal_id"), "extracted_values", ["deal_id"], unique=False)
    op.create_index(
        "ix_extracted_values_entity",
        "extracted_values",
        ["entity_type", "entity_id", "field_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_extracted_values_source_email_id"), "extracted_values", ["source_email_id"], unique=False
    )
    op.create_table(
        "quotes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("deal_id", sa.Uuid(), nullable=False),
        sa.Column("lender_id", sa.Uuid(), nullable=False),
        sa.Column("option_label", sa.Text(), nullable=False),
        sa.Column("source_email_id", sa.Uuid(), nullable=True),
        sa.Column("loan_amount", sa.Numeric(precision=16, scale=2), nullable=True),
        sa.Column("ltv", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("ltc", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("rate_type", sa.String(length=20), nullable=True),
        sa.Column("interest_rate", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("index_name", sa.Text(), nullable=True),
        sa.Column("spread_bps", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("rate_floor", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("term_months", sa.Integer(), nullable=True),
        sa.Column("amortization_months", sa.Integer(), nullable=True),
        sa.Column("interest_only_months", sa.Integer(), nullable=True),
        sa.Column("min_dscr", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("debt_yield", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("origination_fee_pct", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("exit_fee_pct", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("prepayment_terms", sa.Text(), nullable=True),
        sa.Column("recourse", sa.String(length=40), nullable=True),
        sa.Column("extension_options", sa.Text(), nullable=True),
        sa.Column("quote_status", sa.String(length=40), nullable=True),
        sa.Column("expiration_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["deal_id"], ["deals.id"], name=op.f("fk_quotes_deal_id_deals"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["lender_id"], ["lenders.id"], name=op.f("fk_quotes_lender_id_lenders"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["source_email_id"],
            ["emails.id"],
            name=op.f("fk_quotes_source_email_id_emails"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quotes")),
        sa.UniqueConstraint("deal_id", "lender_id", "option_label", name=op.f("uq_quotes_deal_id")),
    )
    op.create_index(op.f("ix_quotes_deal_id"), "quotes", ["deal_id"], unique=False)
    op.create_index(op.f("ix_quotes_lender_id"), "quotes", ["lender_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quotes_lender_id"), table_name="quotes")
    op.drop_index(op.f("ix_quotes_deal_id"), table_name="quotes")
    op.drop_table("quotes")
    op.drop_index(op.f("ix_extracted_values_source_email_id"), table_name="extracted_values")
    op.drop_index("ix_extracted_values_entity", table_name="extracted_values")
    op.drop_index(op.f("ix_extracted_values_deal_id"), table_name="extracted_values")
    op.drop_table("extracted_values")
    op.drop_index(op.f("ix_emails_deal_id"), table_name="emails")
    op.drop_table("emails")
    op.drop_table("lenders")
    op.drop_table("deals")
    # ### end Alembic commands ###
